apiVersion: drasi.io/v1
id: building-comfort-aspire
host: "0.0.0.0"
port: 8080
logLevel: info
persistConfig: false

autoInstallPlugins: true
verifyPlugins: false
plugins:
  - ref: source/grpc
  - ref: reaction/grpc
  - ref: reaction/log

sources: []
queries: []
reactions: []
