kind: Source
apiVersion: v1
name: geo-db
spec:
  kind: E2ETestSource
  services:
    proxy:
      properties:
          PORT: 4002
          SOURCE_ID: "geo-db"
          TEST_RUN_SOURCE_ID: "az_dev_repo.population.test_run_001.geo-db"
          TEST_SERVICE_HOST: "drasi-test-service"
          TEST_SERVICE_PORT: 63123
          RUST_LOG: "debug"
    reactivator:
      properties:
          PORT: 80
          SOURCE_ID: "geo-db"
          TEST_RUN_SOURCE_ID: "az_dev_repo.population.test_run_001.geo-db"
          TEST_SERVICE_HOST: "drasi-test-service"
          TEST_SERVICE_PORT: 63123
          RUST_LOG: "debug"