#!/bin/bash

GREEN="\033[32m"
RESET="\033[0m"

echo -e "${GREEN}\n\nSetting up Kind cluster...${RESET}"
kind create cluster

echo -e "${GREEN}\n\nInstalling Drasi...${RESET}"
drasi init

echo -e "${GREEN}\n\nRegistering E2ETestService SourceProvider with Drasi...${RESET}"
drasi apply -f ./test-source-provider/e2e-test-service-provider.yaml

echo -e "${GREEN}\n\nCreating Test Service Source to host Population Source...${RESET}"
drasi apply -f ./examples/population/kind_drasi/source.yaml
drasi wait -f ./examples/population/kind_drasi/source.yaml -t 120

echo -e "${GREEN}\n\nPort forwarding to enable access the Test Service Web API...${RESET}"
kubectl port-forward -n drasi-system services/geo-db-api 63123:63123 &
sleep 5

echo -e "${GREEN}\n\nAdding Test Repository and Test Source...${RESET}"
curl -i -X POST -H "Content-Type: application/json" -d @examples/population/kind_drasi/add_az_dev_repo.json http://localhost:63123/test_repos
curl -i -X POST -H "Content-Type: application/json" -d @examples/population/kind_drasi/add_population_test_source.json http://localhost:63123/test_run_host/sources

echo -e "${GREEN}\n\nCreating Drasi Continuous Queries...${RESET}"
drasi apply -f examples/population/kind_drasi/query.yaml
drasi wait -f examples/population/kind_drasi/query.yaml -t 120

drasi watch city-population