#!/bin/bash

GREEN="\033[32m"
RESET="\033[0m"

echo -e "${GREEN}\nRunning the E2E Test Service as a local process...${RESET}"
cargo run --manifest-path ./test-service/Cargo.toml -- --config examples/population/local/config.json
