apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasi-test-service
  template:
    metadata:
      labels:
        app: drasi-test-service
    spec:
      containers:
      - name: drasi-test-service
        image: ghcr.io/drasi-project/e2e-test-service:0.1.8
        ports:
        - containerPort: 63123
---
apiVersion: v1
kind: Service
metadata:
  name: drasi-test-service
spec:
  selector:
    app: drasi-test-service
  ports:
    - protocol: TCP
      port: 63123
      targetPort: 63123
  type: NodePort
