apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-test-service
  namespace: drasi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasi-test-service
  template:
    metadata:
      labels:
        app: drasi-test-service
      annotations:
          dapr.io/app-id: drasi-test-service
          dapr.io/config: dapr-config
          dapr.io/enabled: "true"
          dapr.io/sidecar-image: daprio/daprd
    spec:
      containers:
      - name: drasi-test-service
        image: ghcr.io/drasi-project/e2e-test-service:0.2.0
        ports:
        - containerPort: 63123
---
apiVersion: v1
kind: Service
metadata:
  name: drasi-test-service
  namespace: drasi-system  
spec:
  selector:
    app: drasi-test-service
  ports:
    - protocol: TCP
      port: 63123
      targetPort: 63123
  type: NodePort
