kind: QueryContainer
apiVersion: v1
name: default
spec:
  queryHostCount: 1
  defaultStore: rocks
  storage:
    rocks:
      kind: rocksDb
      storageClass: azurefile-csi-premium
      enableArchive: false
      directIo: false
  results:
    MONGO_URI: mongodb://drasi-mongo:27017
    MONGO_RESULT_STORE_DB_NAME: Drasi
    MONGO_RESULT_STORE_COLL_NAME: Results