[package]
name = "gdelt"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38" }
clap = { version = "4.5.18", features = ["derive", "env"] }
log = "0.4"
env_logger = "0.7.1"
anyhow = "1.0.86"
