[workspace]

members = [
  "test-data-store",
  "test-dataset-collector",
  "test-runner",
  "test-runner-service",
  
  # Internal
  "infrastructure/comms-abstractions",
  "infrastructure/comms-dapr",
]

resolver = "2"