kind: ContinuousQuery
apiVersion: v1
name: room-comfort-level
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities-db
        nodes:
          - sourceLabel: Room
  query: >
    MATCH
      (r:Room)
    RETURN
      elementId(r) AS RoomId,
      floor(
        50 + (r.temperature - 72) + (r.humidity - 42) +
        CASE WHEN r.co2 > 500 THEN (r.co2 - 500) / 25 ELSE 0 END
      ) AS ComfortLevel