# Copyright 2025 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Test Infrastructure

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - release/*
            - test-infra-build
        tags:
            - 'v*'
    pull_request: 
        branches:
            - main
            - release/*
            - feature/*

permissions:
    contents: read
    id-token: write

jobs:
    build-e2e-test-framework:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        strategy:
            matrix:
                component: [
                    {
                        label: 'E2E proxy',
                        path: 'e2e-test-framework/proxy',
                        name: 'e2e-proxy'
                    },
                    {
                        label: 'E2E Reactivator',
                        path: 'e2e-test-framework/reactivator',
                        name: 'e2e-reactivator'
                    },
                    {
                        label: 'E2E Test Service',
                        path: 'e2e-test-framework/test-service',
                        name: 'e2e-test-service'
                    }
                ]

        steps:
            - name: Checkout repository
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Set up QEMU
              uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
              with:
                install: true

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                path: /tmp/.buildx-cache
                key: buildx-${{ matrix.component.name }}
                restore-keys: |
                    buildx-${{ matrix.component.name }}
            
            - name: Build
              run: |
                cd ${{ matrix.component.path }}
                DOCKERX_OPTS="--output type=docker,dest=${{ github.workspace }}/${{ matrix.component.name }}.tar --cache-to type=local,dest=/tmp/.buildx-cache,mode=max --cache-from type=local,src=/tmp/.buildx-cache" make